### ISSUE TITLE
hw03 ok.submit() error - seems to want to save it as hw04

### ISSUE THREAD

**Issue by MayaSamet** [ykharitonova/int5-f18-playground#5]
Attempting the initial `_=ok.submit` results in the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'hw04.ipynb'`

**Comment by MayaSamet** [comment]
I issued a pull request to fix the hw03.ok issue that was leading to this. I fixed it in my own notebook and now run into the following when I try to submit:
`Saving notebook... Saved 'hw03.ipynb'.
Submit... 0.0% complete
Could not submit: Late Submission of ucsd/dsc10/sp18/hw04`
Not sure whether this is a bug or something that we're just planning on setting up later

**Comment by ykharitonova** [comment]
I just updated the file by providing the correct endpoint to `hw03.ok`. If it works, then this issue can be closed.
